.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "ARAS.SCHEDULE" "5" "03 May 2015" "" ""
.SH "NAME"
aras.schedule \- Schedule description file for ARAS \- A Radio Automation System.
.SH "DESCRIPTION"
.I aras.schedule
The ARAS schedule file contains the schedule description for ARAS.
.SH "OPTIONS"
.TP 
The ARAS schedule file contains comments and some schedule elements, one of them in each line:

.TP 
Lines with a # character at the beginning are comments.

.TP 
A schedule element is defined in a line as follows:

Day    Time    Block

.TP 
Where:

.TP 
\fBDay\fR can be: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday or Saturday.

.TP 
\fBTime\fR is the time of the beginning of the schedule element in the format HH:MM:SS.

.TP 
\fBBlock\fR is the block associated with the schedule element. Blocks are defined in the aras.block file (see aras.block (5) manual page).

.TP 
An example of a schedule element definition is:

Monday    22:00:00    my_block
.SH "AUTHOR"
.nf 
ARAS software and documentation written by Erasmo Alonso Iglesias <erasmo1982@users.sourceforge.net>
Man page edited by Martin Zelaia <martintxo@sindominio.net>
.SH "SEE ALSO"
.BR aras.conf (5),
.BR aras.block (5),
.BR aras.log (5),
.BR aras\-player (1),
.BR aras\-daemon (1),
.BR aras\-recorder (1)

http://aras.sourceforge.net/
