.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "ARAS-DAEMON" "1" "03 May 2015" "" ""
.SH "NAME"
aras\-daemon \- A Radio Automation System.
.SH "DESCRIPTION"
.I aras\-daemon
is the ARAS program that plays the files or streams as scheduled in the config files, but whitout a GUI interface. There is another program with the same capabilities but with a X GUI (in GTK+): aras (see aras(1) man page).

In your system may have both aras\-daemon.sh and aras\-daemon. The first should be a shell script for call the second in a proper way (passing the proper config file).
.SH "OPTIONS"
.TP 
There is only a option for call the aras\-daemon binary file, its config file (aras.conf).

.TP 
aras\-daemon <configuration file>

.SH "FILES"
.TP 
\fBaras.conf\fR Main configuration file
It may be in any place, since it is invoked in the aras\-daemon startup. Recomended places are /etc/aras/aras.conf, or ~/.aras/aras.conf. See aras.conf (5) manual page for further details. This file is used for all ARAS programs (aras\-player, aras\-daemon and aras\-recorder).

.TP 
\fBaras.schedule\fR Schedule description file
It may be in any place, since it is defined in aras.conf. Recomended places are /etc/aras/aras.schedule, or ~/.aras/aras.schedule. See aras.schedule (5) manual page for further details. This file is used for all ARAS programs (aras\-player, aras\-daemon and aras\-recorder).

.TP 
\fBaras.block\fR Block description file
It may be in any place, since it is defined in aras.conf. Recomended places are /etc/aras/aras.block, or ~/.aras/aras.block. See aras.block (5) manual page for further details. This file is used for all ARAS programs (aras\-player, aras\-daemon and aras\-recorder).

.TP 
\fBaras.log\fR ARAS work log file
It may be in any place, since it is defined in aras.conf. Recomended places are /var/log/aras/aras.log, or ~/.aras/aras.log. See aras.log (5) manual page for further details. This file is used for all ARAS programs (aras\-player, aras\-daemon and aras\-recorder).
.SH "AUTHOR"
.nf 
ARAS software and documentation written by Erasmo Alonso Iglesias <erasmo1982@users.sourceforge.net>
Man page written by Martin Zelaia <martintxo@sindominio.net>
.SH "SEE ALSO"
.BR aras.conf (5),
.BR aras.schedule (5),
.BR aras.block (5),
.BR aras.log (5),
.BR aras\-player (1),
.BR aras\-recorder (1)

http://aras.sourceforge.net/
